spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mobembovf?serverTimezone=UTC
    username: root
    password: lilo.3687
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl:   true
    show-sql:   false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
server:
  port: 8081

